// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

// Ensure FlutterError can be used as a Swift Error in Result types on older Flutter/Swift toolchains.
extension FlutterError: Swift.Error {}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum BackgroundRunOutcome: Int {
  case success = 0
  case retry = 1
  case failure = 2
  case gated = 3
}

enum BackgroundGateReason: Int {
  case none = 0
  case noNetwork = 1
  case authInvalid = 2
  case bindingInvalid = 3
  case repairRequired = 4
  case environmentBlocked = 5
  case localCalendarMissing = 6
  case unknown = 7
}

enum OneOffEnqueuePolicy: Int {
  case keep = 0
  case replace = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct BackgroundRunRequest {
  var trigger: String
  var contractVersion: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> BackgroundRunRequest? {
    let trigger = __pigeon_list[0] as! String
    let contractVersion = __pigeon_list[1] is Int64 ? __pigeon_list[1] as! Int64 : Int64(__pigeon_list[1] as! Int32)

    return BackgroundRunRequest(
      trigger: trigger,
      contractVersion: contractVersion
    )
  }
  func toList() -> [Any?] {
    return [
      trigger,
      contractVersion,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BackgroundRunResult {
  var outcome: BackgroundRunOutcome
  var reason: String
  var gateReason: BackgroundGateReason
  var error: String? = nil
  var contractVersion: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> BackgroundRunResult? {
    let outcome = BackgroundRunOutcome(rawValue: __pigeon_list[0] as! Int)!
    let reason = __pigeon_list[1] as! String
    let gateReason = BackgroundGateReason(rawValue: __pigeon_list[2] as! Int)!
    let error: String? = nilOrValue(__pigeon_list[3])
    let contractVersion = __pigeon_list[4] is Int64 ? __pigeon_list[4] as! Int64 : Int64(__pigeon_list[4] as! Int32)

    return BackgroundRunResult(
      outcome: outcome,
      reason: reason,
      gateReason: gateReason,
      error: error,
      contractVersion: contractVersion
    )
  }
  func toList() -> [Any?] {
    return [
      outcome.rawValue,
      reason,
      gateReason.rawValue,
      error,
      contractVersion,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BackgroundStatusDto {
  var periodicEnabled: Bool
  var lastRunAtMs: Int64? = nil
  var lastOutcome: BackgroundRunOutcome? = nil
  var lastReason: String? = nil
  var lastGateReason: BackgroundGateReason? = nil
  var lastError: String? = nil
  var lastStage: String? = nil
  var lastStageAtMs: Int64? = nil
  var nextScheduledAtMs: Int64? = nil
  var periodicWorkState: String? = nil
  var oneOffWorkState: String? = nil
  var lastFailureStage: String? = nil
  var lastFailureElapsedMs: Int64? = nil
  var lastFailureStep: String? = nil
  var workerRunning: Bool
  var intervalMinutes: Int64
  var contractVersion: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> BackgroundStatusDto? {
    let periodicEnabled = __pigeon_list[0] as! Bool
    let lastRunAtMs: Int64? = isNullish(__pigeon_list[1]) ? nil : (__pigeon_list[1] is Int64? ? __pigeon_list[1] as! Int64? : Int64(__pigeon_list[1] as! Int32))
    var lastOutcome: BackgroundRunOutcome? = nil
    let lastOutcomeEnumVal: Int? = nilOrValue(__pigeon_list[2])
    if let lastOutcomeRawValue = lastOutcomeEnumVal {
      lastOutcome = BackgroundRunOutcome(rawValue: lastOutcomeRawValue)!
    }
    let lastReason: String? = nilOrValue(__pigeon_list[3])
    var lastGateReason: BackgroundGateReason? = nil
    let lastGateReasonEnumVal: Int? = nilOrValue(__pigeon_list[4])
    if let lastGateReasonRawValue = lastGateReasonEnumVal {
      lastGateReason = BackgroundGateReason(rawValue: lastGateReasonRawValue)!
    }
    let lastError: String? = nilOrValue(__pigeon_list[5])
    let lastStage: String? = nilOrValue(__pigeon_list[6])
    let lastStageAtMs: Int64? = isNullish(__pigeon_list[7]) ? nil : (__pigeon_list[7] is Int64? ? __pigeon_list[7] as! Int64? : Int64(__pigeon_list[7] as! Int32))
    let nextScheduledAtMs: Int64? = isNullish(__pigeon_list[8]) ? nil : (__pigeon_list[8] is Int64? ? __pigeon_list[8] as! Int64? : Int64(__pigeon_list[8] as! Int32))
    let periodicWorkState: String? = nilOrValue(__pigeon_list[9])
    let oneOffWorkState: String? = nilOrValue(__pigeon_list[10])
    let lastFailureStage: String? = nilOrValue(__pigeon_list[11])
    let lastFailureElapsedMs: Int64? = isNullish(__pigeon_list[12]) ? nil : (__pigeon_list[12] is Int64? ? __pigeon_list[12] as! Int64? : Int64(__pigeon_list[12] as! Int32))
    let lastFailureStep: String? = nilOrValue(__pigeon_list[13])
    let workerRunning = __pigeon_list[14] as! Bool
    let intervalMinutes = __pigeon_list[15] is Int64 ? __pigeon_list[15] as! Int64 : Int64(__pigeon_list[15] as! Int32)
    let contractVersion = __pigeon_list[16] is Int64 ? __pigeon_list[16] as! Int64 : Int64(__pigeon_list[16] as! Int32)

    return BackgroundStatusDto(
      periodicEnabled: periodicEnabled,
      lastRunAtMs: lastRunAtMs,
      lastOutcome: lastOutcome,
      lastReason: lastReason,
      lastGateReason: lastGateReason,
      lastError: lastError,
      lastStage: lastStage,
      lastStageAtMs: lastStageAtMs,
      nextScheduledAtMs: nextScheduledAtMs,
      periodicWorkState: periodicWorkState,
      oneOffWorkState: oneOffWorkState,
      lastFailureStage: lastFailureStage,
      lastFailureElapsedMs: lastFailureElapsedMs,
      lastFailureStep: lastFailureStep,
      workerRunning: workerRunning,
      intervalMinutes: intervalMinutes,
      contractVersion: contractVersion
    )
  }
  func toList() -> [Any?] {
    return [
      periodicEnabled,
      lastRunAtMs,
      lastOutcome?.rawValue,
      lastReason,
      lastGateReason?.rawValue,
      lastError,
      lastStage,
      lastStageAtMs,
      nextScheduledAtMs,
      periodicWorkState,
      oneOffWorkState,
      lastFailureStage,
      lastFailureElapsedMs,
      lastFailureStep,
      workerRunning,
      intervalMinutes,
      contractVersion,
    ]
  }
}

private class BackgroundSyncControlApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 131:
      return BackgroundStatusDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BackgroundSyncControlApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BackgroundStatusDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BackgroundSyncControlApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BackgroundSyncControlApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BackgroundSyncControlApiCodecWriter(data: data)
  }
}

class BackgroundSyncControlApiCodec: FlutterStandardMessageCodec {
  static let shared = BackgroundSyncControlApiCodec(readerWriter: BackgroundSyncControlApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackgroundSyncControlApi {
  func schedulePeriodic(intervalMinutes: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelPeriodic(completion: @escaping (Result<Void, Error>) -> Void)
  func ensurePeriodicScheduled(intervalMinutes: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func enqueueOneOff(reason: String, expedited: Bool, enqueuePolicy: OneOffEnqueuePolicy, completion: @escaping (Result<Void, Error>) -> Void)
  func getBackgroundStatus(completion: @escaping (Result<BackgroundStatusDto, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackgroundSyncControlApiSetup {
  /// The codec used by BackgroundSyncControlApi.
  static var codec: FlutterStandardMessageCodec { BackgroundSyncControlApiCodec.shared }
  /// Sets up an instance of `BackgroundSyncControlApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackgroundSyncControlApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let schedulePeriodicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.schedulePeriodic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      schedulePeriodicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let intervalMinutesArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        api.schedulePeriodic(intervalMinutes: intervalMinutesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      schedulePeriodicChannel.setMessageHandler(nil)
    }
    let cancelPeriodicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.cancelPeriodic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelPeriodicChannel.setMessageHandler { _, reply in
        api.cancelPeriodic { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelPeriodicChannel.setMessageHandler(nil)
    }
    let ensurePeriodicScheduledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.ensurePeriodicScheduled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      ensurePeriodicScheduledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let intervalMinutesArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        api.ensurePeriodicScheduled(intervalMinutes: intervalMinutesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      ensurePeriodicScheduledChannel.setMessageHandler(nil)
    }
    let enqueueOneOffChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.enqueueOneOff\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enqueueOneOffChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        let expeditedArg = args[1] as! Bool
        let enqueuePolicyArg = OneOffEnqueuePolicy(rawValue: args[2] as! Int)!
        api.enqueueOneOff(reason: reasonArg, expedited: expeditedArg, enqueuePolicy: enqueuePolicyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enqueueOneOffChannel.setMessageHandler(nil)
    }
    let getBackgroundStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.getBackgroundStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBackgroundStatusChannel.setMessageHandler { _, reply in
        api.getBackgroundStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBackgroundStatusChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackgroundSyncRunnerHostApi {
  func notifyBackgroundIsolateReady(contractVersion: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackgroundSyncRunnerHostApiSetup {
  /// The codec used by BackgroundSyncRunnerHostApi.
  /// Sets up an instance of `BackgroundSyncRunnerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackgroundSyncRunnerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let notifyBackgroundIsolateReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.BackgroundSyncRunnerHostApi.notifyBackgroundIsolateReady\(channelSuffix)", binaryMessenger: binaryMessenger)
    if let api = api {
      notifyBackgroundIsolateReadyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contractVersionArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        api.notifyBackgroundIsolateReady(contractVersion: contractVersionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      notifyBackgroundIsolateReadyChannel.setMessageHandler(nil)
    }
  }
}
private class BackgroundSyncRunnerApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BackgroundRunRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return BackgroundRunResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BackgroundSyncRunnerApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BackgroundRunRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BackgroundRunResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BackgroundSyncRunnerApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BackgroundSyncRunnerApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BackgroundSyncRunnerApiCodecWriter(data: data)
  }
}

class BackgroundSyncRunnerApiCodec: FlutterStandardMessageCodec {
  static let shared = BackgroundSyncRunnerApiCodec(readerWriter: BackgroundSyncRunnerApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BackgroundSyncRunnerApiProtocol {
  func pingBackgroundIsolate(completion: @escaping (Result<Bool, FlutterError>) -> Void)
  func runBackgroundSync(request requestArg: BackgroundRunRequest, completion: @escaping (Result<BackgroundRunResult, FlutterError>) -> Void)
}
class BackgroundSyncRunnerApi: BackgroundSyncRunnerApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterStandardMessageCodec {
    return BackgroundSyncRunnerApiCodec.shared
  }
  func pingBackgroundIsolate(completion: @escaping (Result<Bool, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.caleesync.BackgroundSyncRunnerApi.pingBackgroundIsolate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
  func runBackgroundSync(request requestArg: BackgroundRunRequest, completion: @escaping (Result<BackgroundRunResult, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.caleesync.BackgroundSyncRunnerApi.runBackgroundSync\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! BackgroundRunResult
        completion(.success(result))
      }
    }
  }
}
