// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 配置 Pigeon 生成代码的路径
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCalendar {
  var id: String? = nil
  var name: String? = nil
  var color: String? = nil
  var isReadOnly: Bool? = nil
  var supportsEvents: Bool? = nil
  var supportsTasks: Bool? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> PlatformCalendar? {
    let id: String? = nilOrValue(__pigeon_list[0])
    let name: String? = nilOrValue(__pigeon_list[1])
    let color: String? = nilOrValue(__pigeon_list[2])
    let isReadOnly: Bool? = nilOrValue(__pigeon_list[3])
    let supportsEvents: Bool? = nilOrValue(__pigeon_list[4])
    let supportsTasks: Bool? = nilOrValue(__pigeon_list[5])

    return PlatformCalendar(
      id: id,
      name: name,
      color: color,
      isReadOnly: isReadOnly,
      supportsEvents: supportsEvents,
      supportsTasks: supportsTasks
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      color,
      isReadOnly,
      supportsEvents,
      supportsTasks,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformItem {
  var localId: String? = nil
  var uid: String? = nil
  var title: String? = nil
  var notes: String? = nil
  var location: String? = nil
  var startTime: Int64? = nil
  var endTime: Int64? = nil
  var lastModified: Int64? = nil
  var isTask: Bool? = nil
  var isAllDay: Bool? = nil
  var status: Int64? = nil
  var priority: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> PlatformItem? {
    let localId: String? = nilOrValue(__pigeon_list[0])
    let uid: String? = nilOrValue(__pigeon_list[1])
    let title: String? = nilOrValue(__pigeon_list[2])
    let notes: String? = nilOrValue(__pigeon_list[3])
    let location: String? = nilOrValue(__pigeon_list[4])
    let startTime: Int64? = isNullish(__pigeon_list[5]) ? nil : (__pigeon_list[5] is Int64? ? __pigeon_list[5] as! Int64? : Int64(__pigeon_list[5] as! Int32))
    let endTime: Int64? = isNullish(__pigeon_list[6]) ? nil : (__pigeon_list[6] is Int64? ? __pigeon_list[6] as! Int64? : Int64(__pigeon_list[6] as! Int32))
    let lastModified: Int64? = isNullish(__pigeon_list[7]) ? nil : (__pigeon_list[7] is Int64? ? __pigeon_list[7] as! Int64? : Int64(__pigeon_list[7] as! Int32))
    let isTask: Bool? = nilOrValue(__pigeon_list[8])
    let isAllDay: Bool? = nilOrValue(__pigeon_list[9])
    let status: Int64? = isNullish(__pigeon_list[10]) ? nil : (__pigeon_list[10] is Int64? ? __pigeon_list[10] as! Int64? : Int64(__pigeon_list[10] as! Int32))
    let priority: Int64? = isNullish(__pigeon_list[11]) ? nil : (__pigeon_list[11] is Int64? ? __pigeon_list[11] as! Int64? : Int64(__pigeon_list[11] as! Int32))

    return PlatformItem(
      localId: localId,
      uid: uid,
      title: title,
      notes: notes,
      location: location,
      startTime: startTime,
      endTime: endTime,
      lastModified: lastModified,
      isTask: isTask,
      isAllDay: isAllDay,
      status: status,
      priority: priority
    )
  }
  func toList() -> [Any?] {
    return [
      localId,
      uid,
      title,
      notes,
      location,
      startTime,
      endTime,
      lastModified,
      isTask,
      isAllDay,
      status,
      priority,
    ]
  }
}

private class NativeCalendarApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PlatformCalendar.fromList(self.readValue() as! [Any?])
    case 129:
      return PlatformItem.fromList(self.readValue() as! [Any?])
    case 130:
      return PlatformItem.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeCalendarApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformCalendar {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformItem {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformItem {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeCalendarApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeCalendarApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeCalendarApiCodecWriter(data: data)
  }
}

class NativeCalendarApiCodec: FlutterStandardMessageCodec {
  static let shared = NativeCalendarApiCodec(readerWriter: NativeCalendarApiCodecReaderWriter())
}

/// 定义原生侧必须实现的方法
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeCalendarApi {
  /// 获取日历列表前请求权限
  func requestPermission(forTask: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  /// 获取所有可同步的日历
  func getCalendars() throws -> [PlatformCalendar]
  /// 获取指定日历在时间范围内的所有条目
  /// 注意：Android 上由于系统限制，可能只返回 Event
  func getItems(calendarId: String, startMs: Int64, endMs: Int64) throws -> [PlatformItem]
  /// 创建或更新条目
  /// 返回写入成功后的系统 localId
  func upsertItem(calendarId: String, item: PlatformItem, completion: @escaping (Result<String, Error>) -> Void)
  /// 根据 ID 删除条目
  func deleteItem(localId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeCalendarApiSetup {
  /// The codec used by NativeCalendarApi.
  static var codec: FlutterStandardMessageCodec { NativeCalendarApiCodec.shared }
  /// Sets up an instance of `NativeCalendarApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeCalendarApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 获取日历列表前请求权限
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let forTaskArg = args[0] as! Bool
        api.requestPermission(forTask: forTaskArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    /// 获取所有可同步的日历
    let getCalendarsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.getCalendars\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCalendarsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCalendars()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCalendarsChannel.setMessageHandler(nil)
    }
    /// 获取指定日历在时间范围内的所有条目
    /// 注意：Android 上由于系统限制，可能只返回 Event
    let getItemsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.getItems\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getItemsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        let startMsArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        let endMsArg = args[2] is Int64 ? args[2] as! Int64 : Int64(args[2] as! Int32)
        do {
          let result = try api.getItems(calendarId: calendarIdArg, startMs: startMsArg, endMs: endMsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getItemsChannel.setMessageHandler(nil)
    }
    /// 创建或更新条目
    /// 返回写入成功后的系统 localId
    let upsertItemChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.upsertItem\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      upsertItemChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        let itemArg = args[1] as! PlatformItem
        api.upsertItem(calendarId: calendarIdArg, item: itemArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      upsertItemChannel.setMessageHandler(nil)
    }
    /// 根据 ID 删除条目
    let deleteItemChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteItem\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteItemChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localIdArg = args[0] as! String
        api.deleteItem(localId: localIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteItemChannel.setMessageHandler(nil)
    }
  }
}
