// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Calendar data contract exposed via Pigeon.
///
/// Scope (first milestone):
/// - List calendars
/// - List events within a time window
///
/// Note: Permission handling is done via permission_handler in Flutter,
/// not through this Pigeon API.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TimeWindow {
  /// Inclusive UTC start timestamp in milliseconds.
  var startMillis: Int64
  /// Exclusive UTC end timestamp in milliseconds.
  var endMillis: Int64
  /// Optional filter for specific calendar IDs (device identifiers).
  var calendarIds: [Int64?]? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> TimeWindow? {
    let startMillis = __pigeon_list[0] is Int64 ? __pigeon_list[0] as! Int64 : Int64(__pigeon_list[0] as! Int32)
    let endMillis = __pigeon_list[1] is Int64 ? __pigeon_list[1] as! Int64 : Int64(__pigeon_list[1] as! Int32)
    let calendarIds: [Int64?]? = nilOrValue(__pigeon_list[2])

    return TimeWindow(
      startMillis: startMillis,
      endMillis: endMillis,
      calendarIds: calendarIds
    )
  }
  func toList() -> [Any?] {
    return [
      startMillis,
      endMillis,
      calendarIds,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonCalendar {
  /// Device-level calendar identifier (Calendar Provider / EventKit).
  var id: Int64
  var accountName: String
  var accountType: String
  var ownerAccount: String? = nil
  var name: String? = nil
  var displayName: String? = nil
  var color: Int64
  var visible: Bool
  var syncEvents: Bool
  var isPrimary: Bool
  var isLocal: Bool
  var accessLevel: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> PigeonCalendar? {
    let id = __pigeon_list[0] is Int64 ? __pigeon_list[0] as! Int64 : Int64(__pigeon_list[0] as! Int32)
    let accountName = __pigeon_list[1] as! String
    let accountType = __pigeon_list[2] as! String
    let ownerAccount: String? = nilOrValue(__pigeon_list[3])
    let name: String? = nilOrValue(__pigeon_list[4])
    let displayName: String? = nilOrValue(__pigeon_list[5])
    let color = __pigeon_list[6] is Int64 ? __pigeon_list[6] as! Int64 : Int64(__pigeon_list[6] as! Int32)
    let visible = __pigeon_list[7] as! Bool
    let syncEvents = __pigeon_list[8] as! Bool
    let isPrimary = __pigeon_list[9] as! Bool
    let isLocal = __pigeon_list[10] as! Bool
    let accessLevel = __pigeon_list[11] is Int64 ? __pigeon_list[11] as! Int64 : Int64(__pigeon_list[11] as! Int32)

    return PigeonCalendar(
      id: id,
      accountName: accountName,
      accountType: accountType,
      ownerAccount: ownerAccount,
      name: name,
      displayName: displayName,
      color: color,
      visible: visible,
      syncEvents: syncEvents,
      isPrimary: isPrimary,
      isLocal: isLocal,
      accessLevel: accessLevel
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      accountName,
      accountType,
      ownerAccount,
      name,
      displayName,
      color,
      visible,
      syncEvents,
      isPrimary,
      isLocal,
      accessLevel,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonEvent {
  /// Device-level event identifier (Calendar Provider / EventKit).
  var id: String
  var calendarId: String
  var title: String
  var startMillis: Int64
  var endMillis: Int64
  var description: String? = nil
  var location: String? = nil
  var allDay: Bool
  var timeZone: String? = nil
  /// RRULE string (e.g. FREQ=WEEKLY;BYDAY=MO,WE,FR).
  var recurrenceRule: String? = nil
  /// UTC millis for EXDATE-like exceptions.
  var recurrenceExceptionMillis: [Int64?]? = nil
  /// Attendee emails or identifiers.
  var attendees: [String?]? = nil
  var organizer: String? = nil
  var status: String? = nil
  var etag: String? = nil
  var updatedAtMillis: Int64? = nil
  var isCanceled: Bool

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> PigeonEvent? {
    let id = __pigeon_list[0] as! String
    let calendarId = __pigeon_list[1] as! String
    let title = __pigeon_list[2] as! String
    let startMillis = __pigeon_list[3] is Int64 ? __pigeon_list[3] as! Int64 : Int64(__pigeon_list[3] as! Int32)
    let endMillis = __pigeon_list[4] is Int64 ? __pigeon_list[4] as! Int64 : Int64(__pigeon_list[4] as! Int32)
    let description: String? = nilOrValue(__pigeon_list[5])
    let location: String? = nilOrValue(__pigeon_list[6])
    let allDay = __pigeon_list[7] as! Bool
    let timeZone: String? = nilOrValue(__pigeon_list[8])
    let recurrenceRule: String? = nilOrValue(__pigeon_list[9])
    let recurrenceExceptionMillis: [Int64?]? = nilOrValue(__pigeon_list[10])
    let attendees: [String?]? = nilOrValue(__pigeon_list[11])
    let organizer: String? = nilOrValue(__pigeon_list[12])
    let status: String? = nilOrValue(__pigeon_list[13])
    let etag: String? = nilOrValue(__pigeon_list[14])
    let updatedAtMillis: Int64? = isNullish(__pigeon_list[15]) ? nil : (__pigeon_list[15] is Int64? ? __pigeon_list[15] as! Int64? : Int64(__pigeon_list[15] as! Int32))
    let isCanceled = __pigeon_list[16] as! Bool

    return PigeonEvent(
      id: id,
      calendarId: calendarId,
      title: title,
      startMillis: startMillis,
      endMillis: endMillis,
      description: description,
      location: location,
      allDay: allDay,
      timeZone: timeZone,
      recurrenceRule: recurrenceRule,
      recurrenceExceptionMillis: recurrenceExceptionMillis,
      attendees: attendees,
      organizer: organizer,
      status: status,
      etag: etag,
      updatedAtMillis: updatedAtMillis,
      isCanceled: isCanceled
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      calendarId,
      title,
      startMillis,
      endMillis,
      description,
      location,
      allDay,
      timeZone,
      recurrenceRule,
      recurrenceExceptionMillis,
      attendees,
      organizer,
      status,
      etag,
      updatedAtMillis,
      isCanceled,
    ]
  }
}
private class CalendarHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PigeonCalendar.fromList(self.readValue() as! [Any?])
    case 129:
      return PigeonEvent.fromList(self.readValue() as! [Any?])
    case 130:
      return TimeWindow.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CalendarHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonCalendar {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? TimeWindow {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CalendarHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CalendarHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CalendarHostApiCodecWriter(data: data)
  }
}

class CalendarHostApiCodec: FlutterStandardMessageCodec {
  static let shared = CalendarHostApiCodec(readerWriter: CalendarHostApiCodecReaderWriter())
}

/// Host API implemented on Android/iOS. Flutter calls into this.
///
/// Note: Permission must be granted before calling these methods.
/// Use permission_handler in Flutter to request calendar permissions.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CalendarHostApi {
  /// List calendars available on the device.
  ///
  /// Throws if permission is not granted.
  func listCalendars() throws -> [PigeonCalendar?]
  /// List events in the given UTC time window (can filter calendars).
  ///
  /// Throws if permission is not granted.
  func listEvents(window: TimeWindow) throws -> [PigeonEvent?]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CalendarHostApiSetup {
  /// The codec used by CalendarHostApi.
  static var codec: FlutterStandardMessageCodec { CalendarHostApiCodec.shared }
  /// Sets up an instance of `CalendarHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CalendarHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// List calendars available on the device.
    ///
    /// Throws if permission is not granted.
    let listCalendarsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.calendar_api.CalendarHostApi.listCalendars\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listCalendarsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listCalendars()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listCalendarsChannel.setMessageHandler(nil)
    }
    /// List events in the given UTC time window (can filter calendars).
    ///
    /// Throws if permission is not granted.
    let listEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.calendar_api.CalendarHostApi.listEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listEventsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let windowArg = args[0] as! TimeWindow
        do {
          let result = try api.listEvents(window: windowArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listEventsChannel.setMessageHandler(nil)
    }
  }
}
