// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 配置 Pigeon 生成代码的路径
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCalendar {
  var id: String? = nil
  var name: String? = nil
  var accountName: String? = nil
  var accountType: String? = nil
  var color: String? = nil
  var isReadOnly: Bool? = nil
  var supportsEvents: Bool? = nil
  var supportsTasks: Bool? = nil
  var isSubscription: Bool? = nil
  var subscriptionUrl: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> PlatformCalendar? {
    let id: String? = nilOrValue(__pigeon_list[0])
    let name: String? = nilOrValue(__pigeon_list[1])
    let accountName: String? = nilOrValue(__pigeon_list[2])
    let accountType: String? = nilOrValue(__pigeon_list[3])
    let color: String? = nilOrValue(__pigeon_list[4])
    let isReadOnly: Bool? = nilOrValue(__pigeon_list[5])
    let supportsEvents: Bool? = nilOrValue(__pigeon_list[6])
    let supportsTasks: Bool? = nilOrValue(__pigeon_list[7])
    let isSubscription: Bool? = nilOrValue(__pigeon_list[8])
    let subscriptionUrl: String? = nilOrValue(__pigeon_list[9])

    return PlatformCalendar(
      id: id,
      name: name,
      accountName: accountName,
      accountType: accountType,
      color: color,
      isReadOnly: isReadOnly,
      supportsEvents: supportsEvents,
      supportsTasks: supportsTasks,
      isSubscription: isSubscription,
      subscriptionUrl: subscriptionUrl
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      accountName,
      accountType,
      color,
      isReadOnly,
      supportsEvents,
      supportsTasks,
      isSubscription,
      subscriptionUrl,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformItem {
  var localId: String? = nil
  var uid: String? = nil
  var title: String? = nil
  var notes: String? = nil
  var location: String? = nil
  var startTime: Int64? = nil
  var endTime: Int64? = nil
  var lastModified: Int64? = nil
  var isTask: Bool? = nil
  var isAllDay: Bool? = nil
  var status: Int64? = nil
  var priority: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> PlatformItem? {
    let localId: String? = nilOrValue(__pigeon_list[0])
    let uid: String? = nilOrValue(__pigeon_list[1])
    let title: String? = nilOrValue(__pigeon_list[2])
    let notes: String? = nilOrValue(__pigeon_list[3])
    let location: String? = nilOrValue(__pigeon_list[4])
    let startTime: Int64? = isNullish(__pigeon_list[5]) ? nil : (__pigeon_list[5] is Int64? ? __pigeon_list[5] as! Int64? : Int64(__pigeon_list[5] as! Int32))
    let endTime: Int64? = isNullish(__pigeon_list[6]) ? nil : (__pigeon_list[6] is Int64? ? __pigeon_list[6] as! Int64? : Int64(__pigeon_list[6] as! Int32))
    let lastModified: Int64? = isNullish(__pigeon_list[7]) ? nil : (__pigeon_list[7] is Int64? ? __pigeon_list[7] as! Int64? : Int64(__pigeon_list[7] as! Int32))
    let isTask: Bool? = nilOrValue(__pigeon_list[8])
    let isAllDay: Bool? = nilOrValue(__pigeon_list[9])
    let status: Int64? = isNullish(__pigeon_list[10]) ? nil : (__pigeon_list[10] is Int64? ? __pigeon_list[10] as! Int64? : Int64(__pigeon_list[10] as! Int32))
    let priority: Int64? = isNullish(__pigeon_list[11]) ? nil : (__pigeon_list[11] is Int64? ? __pigeon_list[11] as! Int64? : Int64(__pigeon_list[11] as! Int32))

    return PlatformItem(
      localId: localId,
      uid: uid,
      title: title,
      notes: notes,
      location: location,
      startTime: startTime,
      endTime: endTime,
      lastModified: lastModified,
      isTask: isTask,
      isAllDay: isAllDay,
      status: status,
      priority: priority
    )
  }
  func toList() -> [Any?] {
    return [
      localId,
      uid,
      title,
      notes,
      location,
      startTime,
      endTime,
      lastModified,
      isTask,
      isAllDay,
      status,
      priority,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CalendarEventRequest {
  var calendarId: String
  var title: String
  var start: Int64
  var end: Int64
  var notes: String? = nil
  var uid: String
  var eventId: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> CalendarEventRequest? {
    let calendarId = __pigeon_list[0] as! String
    let title = __pigeon_list[1] as! String
    let start = __pigeon_list[2] is Int64 ? __pigeon_list[2] as! Int64 : Int64(__pigeon_list[2] as! Int32)
    let end = __pigeon_list[3] is Int64 ? __pigeon_list[3] as! Int64 : Int64(__pigeon_list[3] as! Int32)
    let notes: String? = nilOrValue(__pigeon_list[4])
    let uid = __pigeon_list[5] as! String
    let eventId: String? = nilOrValue(__pigeon_list[6])

    return CalendarEventRequest(
      calendarId: calendarId,
      title: title,
      start: start,
      end: end,
      notes: notes,
      uid: uid,
      eventId: eventId
    )
  }
  func toList() -> [Any?] {
    return [
      calendarId,
      title,
      start,
      end,
      notes,
      uid,
      eventId,
    ]
  }
}

private class NativeCalendarApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return CalendarEventRequest.fromList(self.readValue() as! [Any?])
    case 129:
      return PlatformCalendar.fromList(self.readValue() as! [Any?])
    case 130:
      return PlatformItem.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeCalendarApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CalendarEventRequest {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCalendar {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformItem {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeCalendarApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeCalendarApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeCalendarApiCodecWriter(data: data)
  }
}

class NativeCalendarApiCodec: FlutterStandardMessageCodec {
  static let shared = NativeCalendarApiCodec(readerWriter: NativeCalendarApiCodecReaderWriter())
}

/// 定义原生侧必须实现的方法
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeCalendarApi {
  /// 获取日历列表前请求权限
  func requestPermission(forTask: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  /// 获取所有可同步的日历
  func getCalendars() throws -> [PlatformCalendar]
  /// 获取指定日历在时间范围内的所有条目
  /// 注意：Android 上由于系统限制，可能只返回 Event
  func getEvents(calendarId: String, startMs: Int64, endMs: Int64) throws -> [PlatformItem]
  /// 🚀 关键新增：在手机系统里创建一个新的日历账簿
  /// 返回系统分配的数字 ID (String 形式的 Long)
  func createCalendar(displayName: String, accountName: String, color: Int64, completion: @escaping (Result<String?, Error>) -> Void)
  /// 🚀 关键新增：根据 ID 删除整个日历账簿
  /// Android 上删除日历会自动联级删除该日历下的所有事件 (Events)
  func deleteCalendar(calendarId: String, accountName: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func createEvent(calendarId: String, title: String, start: Int64, end: Int64, notes: String?, uid: String?, completion: @escaping (Result<String?, Error>) -> Void)
  func createOrUpdateEvent(request: CalendarEventRequest, completion: @escaping (Result<String?, Error>) -> Void)
  /// 获取指定日历下所有事件的 ID 列表（用于检测本地删除了哪些）
  func getSystemEventIds(calendarId: String) throws -> [String]
  /// 根据 ID 删除本地事件（用于同步云端的删除操作）
  func deleteEvent(eventId: String) throws -> Bool
  func modifyCalendarTitle(calendarId: String, newTitle: String, accountName: String, accountType: String, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeCalendarApiSetup {
  /// The codec used by NativeCalendarApi.
  static var codec: FlutterStandardMessageCodec { NativeCalendarApiCodec.shared }
  /// Sets up an instance of `NativeCalendarApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeCalendarApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 获取日历列表前请求权限
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let forTaskArg = args[0] as! Bool
        api.requestPermission(forTask: forTaskArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    /// 获取所有可同步的日历
    let getCalendarsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.getCalendars\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCalendarsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCalendars()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCalendarsChannel.setMessageHandler(nil)
    }
    /// 获取指定日历在时间范围内的所有条目
    /// 注意：Android 上由于系统限制，可能只返回 Event
    let getEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.getEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEventsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        let startMsArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        let endMsArg = args[2] is Int64 ? args[2] as! Int64 : Int64(args[2] as! Int32)
        do {
          let result = try api.getEvents(calendarId: calendarIdArg, startMs: startMsArg, endMs: endMsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getEventsChannel.setMessageHandler(nil)
    }
    /// 🚀 关键新增：在手机系统里创建一个新的日历账簿
    /// 返回系统分配的数字 ID (String 形式的 Long)
    let createCalendarChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.createCalendar\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createCalendarChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayNameArg = args[0] as! String
        let accountNameArg = args[1] as! String
        let colorArg = args[2] is Int64 ? args[2] as! Int64 : Int64(args[2] as! Int32)
        api.createCalendar(displayName: displayNameArg, accountName: accountNameArg, color: colorArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createCalendarChannel.setMessageHandler(nil)
    }
    /// 🚀 关键新增：根据 ID 删除整个日历账簿
    /// Android 上删除日历会自动联级删除该日历下的所有事件 (Events)
    let deleteCalendarChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteCalendar\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteCalendarChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        let accountNameArg = args[1] as! String
        api.deleteCalendar(calendarId: calendarIdArg, accountName: accountNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteCalendarChannel.setMessageHandler(nil)
    }
    let createEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.createEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        let titleArg = args[1] as! String
        let startArg = args[2] is Int64 ? args[2] as! Int64 : Int64(args[2] as! Int32)
        let endArg = args[3] is Int64 ? args[3] as! Int64 : Int64(args[3] as! Int32)
        let notesArg: String? = nilOrValue(args[4])
        let uidArg: String? = nilOrValue(args[5])
        api.createEvent(calendarId: calendarIdArg, title: titleArg, start: startArg, end: endArg, notes: notesArg, uid: uidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createEventChannel.setMessageHandler(nil)
    }
    let createOrUpdateEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.createOrUpdateEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createOrUpdateEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CalendarEventRequest
        api.createOrUpdateEvent(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createOrUpdateEventChannel.setMessageHandler(nil)
    }
    /// 获取指定日历下所有事件的 ID 列表（用于检测本地删除了哪些）
    let getSystemEventIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.getSystemEventIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSystemEventIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        do {
          let result = try api.getSystemEventIds(calendarId: calendarIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSystemEventIdsChannel.setMessageHandler(nil)
    }
    /// 根据 ID 删除本地事件（用于同步云端的删除操作）
    let deleteEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventIdArg = args[0] as! String
        do {
          let result = try api.deleteEvent(eventId: eventIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteEventChannel.setMessageHandler(nil)
    }
    let modifyCalendarTitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.caleesync.NativeCalendarApi.modifyCalendarTitle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      modifyCalendarTitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let calendarIdArg = args[0] as! String
        let newTitleArg = args[1] as! String
        let accountNameArg = args[2] as! String
        let accountTypeArg = args[3] as! String
        api.modifyCalendarTitle(calendarId: calendarIdArg, newTitle: newTitleArg, accountName: accountNameArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      modifyCalendarTitleChannel.setMessageHandler(nil)
    }
  }
}
