// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nextcloud.caleesync

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Calendar data contract exposed via Pigeon.
 *
 * Scope (first milestone):
 * - List calendars
 * - List events within a time window
 *
 * Note: Permission handling is done via permission_handler in Flutter,
 * not through this Pigeon API.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TimeWindow (
  /** Inclusive UTC start timestamp in milliseconds. */
  val startMillis: Long,
  /** Exclusive UTC end timestamp in milliseconds. */
  val endMillis: Long,
  /** Optional filter for specific calendar IDs (device identifiers). */
  val calendarIds: List<Long?>? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): TimeWindow {
      val startMillis = __pigeon_list[0].let { num -> if (num is Int) num.toLong() else num as Long }
      val endMillis = __pigeon_list[1].let { num -> if (num is Int) num.toLong() else num as Long }
      val calendarIds = __pigeon_list[2] as List<Long?>?
      return TimeWindow(startMillis, endMillis, calendarIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      startMillis,
      endMillis,
      calendarIds,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonCalendar (
  /** Device-level calendar identifier (Calendar Provider / EventKit). */
  val id: Long,
  val accountName: String,
  val accountType: String,
  val ownerAccount: String? = null,
  val name: String? = null,
  val displayName: String? = null,
  val color: Long,
  val visible: Boolean,
  val syncEvents: Boolean,
  val isPrimary: Boolean,
  val isLocal: Boolean,
  val accessLevel: Long

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): PigeonCalendar {
      val id = __pigeon_list[0].let { num -> if (num is Int) num.toLong() else num as Long }
      val accountName = __pigeon_list[1] as String
      val accountType = __pigeon_list[2] as String
      val ownerAccount = __pigeon_list[3] as String?
      val name = __pigeon_list[4] as String?
      val displayName = __pigeon_list[5] as String?
      val color = __pigeon_list[6].let { num -> if (num is Int) num.toLong() else num as Long }
      val visible = __pigeon_list[7] as Boolean
      val syncEvents = __pigeon_list[8] as Boolean
      val isPrimary = __pigeon_list[9] as Boolean
      val isLocal = __pigeon_list[10] as Boolean
      val accessLevel = __pigeon_list[11].let { num -> if (num is Int) num.toLong() else num as Long }
      return PigeonCalendar(id, accountName, accountType, ownerAccount, name, displayName, color, visible, syncEvents, isPrimary, isLocal, accessLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      accountName,
      accountType,
      ownerAccount,
      name,
      displayName,
      color,
      visible,
      syncEvents,
      isPrimary,
      isLocal,
      accessLevel,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonEvent (
  /** Device-level event identifier (Calendar Provider / EventKit). */
  val id: String,
  val calendarId: String,
  val title: String,
  val startMillis: Long,
  val endMillis: Long,
  val description: String? = null,
  val location: String? = null,
  val allDay: Boolean,
  val timeZone: String? = null,
  /** RRULE string (e.g. FREQ=WEEKLY;BYDAY=MO,WE,FR). */
  val recurrenceRule: String? = null,
  /** UTC millis for EXDATE-like exceptions. */
  val recurrenceExceptionMillis: List<Long?>? = null,
  /** Attendee emails or identifiers. */
  val attendees: List<String?>? = null,
  val organizer: String? = null,
  val status: String? = null,
  val etag: String? = null,
  val updatedAtMillis: Long? = null,
  val isCanceled: Boolean

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): PigeonEvent {
      val id = __pigeon_list[0] as String
      val calendarId = __pigeon_list[1] as String
      val title = __pigeon_list[2] as String
      val startMillis = __pigeon_list[3].let { num -> if (num is Int) num.toLong() else num as Long }
      val endMillis = __pigeon_list[4].let { num -> if (num is Int) num.toLong() else num as Long }
      val description = __pigeon_list[5] as String?
      val location = __pigeon_list[6] as String?
      val allDay = __pigeon_list[7] as Boolean
      val timeZone = __pigeon_list[8] as String?
      val recurrenceRule = __pigeon_list[9] as String?
      val recurrenceExceptionMillis = __pigeon_list[10] as List<Long?>?
      val attendees = __pigeon_list[11] as List<String?>?
      val organizer = __pigeon_list[12] as String?
      val status = __pigeon_list[13] as String?
      val etag = __pigeon_list[14] as String?
      val updatedAtMillis = __pigeon_list[15].let { num -> if (num is Int) num.toLong() else num as Long? }
      val isCanceled = __pigeon_list[16] as Boolean
      return PigeonEvent(id, calendarId, title, startMillis, endMillis, description, location, allDay, timeZone, recurrenceRule, recurrenceExceptionMillis, attendees, organizer, status, etag, updatedAtMillis, isCanceled)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      calendarId,
      title,
      startMillis,
      endMillis,
      description,
      location,
      allDay,
      timeZone,
      recurrenceRule,
      recurrenceExceptionMillis,
      attendees,
      organizer,
      status,
      etag,
      updatedAtMillis,
      isCanceled,
    )
  }
}
private object CalendarHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonCalendar.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonEvent.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TimeWindow.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonCalendar -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PigeonEvent -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TimeWindow -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API implemented on Android/iOS. Flutter calls into this.
 *
 * Note: Permission must be granted before calling these methods.
 * Use permission_handler in Flutter to request calendar permissions.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CalendarHostApi {
  /**
   * List calendars available on the device.
   *
   * Throws if permission is not granted.
   */
  fun listCalendars(): List<PigeonCalendar?>
  /**
   * List events in the given UTC time window (can filter calendars).
   *
   * Throws if permission is not granted.
   */
  fun listEvents(window: TimeWindow): List<PigeonEvent?>

  companion object {
    /** The codec used by CalendarHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CalendarHostApiCodec
    }
    /** Sets up an instance of `CalendarHostApi` to handle messages through the `binaryMessenger`. */
    fun setUp(binaryMessenger: BinaryMessenger, api: CalendarHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.calendar_api.CalendarHostApi.listCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.listCalendars())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.calendar_api.CalendarHostApi.listEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val windowArg = args[0] as TimeWindow
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.listEvents(windowArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
