// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nextcloud.caleesync

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 配置 Pigeon 生成代码的路径
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformCalendar (
  val id: String? = null,
  val name: String? = null,
  val accountName: String? = null,
  val accountType: String? = null,
  val color: String? = null,
  val isReadOnly: Boolean? = null,
  val supportsEvents: Boolean? = null,
  val supportsTasks: Boolean? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): PlatformCalendar {
      val id = __pigeon_list[0] as String?
      val name = __pigeon_list[1] as String?
      val accountName = __pigeon_list[2] as String?
      val accountType = __pigeon_list[3] as String?
      val color = __pigeon_list[4] as String?
      val isReadOnly = __pigeon_list[5] as Boolean?
      val supportsEvents = __pigeon_list[6] as Boolean?
      val supportsTasks = __pigeon_list[7] as Boolean?
      return PlatformCalendar(id, name, accountName, accountType, color, isReadOnly, supportsEvents, supportsTasks)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      name,
      accountName,
      accountType,
      color,
      isReadOnly,
      supportsEvents,
      supportsTasks,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformItem (
  val localId: String? = null,
  val uid: String? = null,
  val title: String? = null,
  val notes: String? = null,
  val location: String? = null,
  val startTime: Long? = null,
  val endTime: Long? = null,
  val lastModified: Long? = null,
  val isTask: Boolean? = null,
  val isAllDay: Boolean? = null,
  val status: Long? = null,
  val priority: Long? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): PlatformItem {
      val localId = __pigeon_list[0] as String?
      val uid = __pigeon_list[1] as String?
      val title = __pigeon_list[2] as String?
      val notes = __pigeon_list[3] as String?
      val location = __pigeon_list[4] as String?
      val startTime = __pigeon_list[5].let { num -> if (num is Int) num.toLong() else num as Long? }
      val endTime = __pigeon_list[6].let { num -> if (num is Int) num.toLong() else num as Long? }
      val lastModified = __pigeon_list[7].let { num -> if (num is Int) num.toLong() else num as Long? }
      val isTask = __pigeon_list[8] as Boolean?
      val isAllDay = __pigeon_list[9] as Boolean?
      val status = __pigeon_list[10].let { num -> if (num is Int) num.toLong() else num as Long? }
      val priority = __pigeon_list[11].let { num -> if (num is Int) num.toLong() else num as Long? }
      return PlatformItem(localId, uid, title, notes, location, startTime, endTime, lastModified, isTask, isAllDay, status, priority)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      localId,
      uid,
      title,
      notes,
      location,
      startTime,
      endTime,
      lastModified,
      isTask,
      isAllDay,
      status,
      priority,
    )
  }
}

private object NativeCalendarApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCalendar.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformItem.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformCalendar -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PlatformItem -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 定义原生侧必须实现的方法
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeCalendarApi {
  /** 获取日历列表前请求权限 */
  fun requestPermission(forTask: Boolean, callback: (Result<Boolean>) -> Unit)
  /** 获取所有可同步的日历 */
  fun getCalendars(): List<PlatformCalendar>
  /**
   * 获取指定日历在时间范围内的所有条目
   * 注意：Android 上由于系统限制，可能只返回 Event
   */
  fun getEvents(calendarId: String, startMs: Long, endMs: Long): List<PlatformItem>
  fun createEvent(calendarId: String, title: String, start: Long, end: Long, notes: String?, uid: String?, callback: (Result<String?>) -> Unit)
  /** 获取指定日历下所有事件的 ID 列表（用于检测本地删除了哪些） */
  fun getSystemEventIds(calendarId: String): List<String>
  /** 根据 ID 删除本地事件（用于同步云端的删除操作） */
  fun deleteEvent(eventId: String): Boolean

  companion object {
    /** The codec used by NativeCalendarApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeCalendarApiCodec
    }
    /** Sets up an instance of `NativeCalendarApi` to handle messages through the `binaryMessenger`. */
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeCalendarApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val forTaskArg = args[0] as Boolean
            api.requestPermission(forTaskArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.getCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.getCalendars())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.getEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val startMsArg = args[1].let { num -> if (num is Int) num.toLong() else num as Long }
            val endMsArg = args[2].let { num -> if (num is Int) num.toLong() else num as Long }
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.getEvents(calendarIdArg, startMsArg, endMsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.createEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val titleArg = args[1] as String
            val startArg = args[2].let { num -> if (num is Int) num.toLong() else num as Long }
            val endArg = args[3].let { num -> if (num is Int) num.toLong() else num as Long }
            val notesArg = args[4] as String?
            val uidArg = args[5] as String?
            api.createEvent(calendarIdArg, titleArg, startArg, endArg, notesArg, uidArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.getSystemEventIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.getSystemEventIds(calendarIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.deleteEvent(eventIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
