// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.calee.caleesync

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
private class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 配置 Pigeon 生成代码的路径
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformCalendar (
  val id: String? = null,
  val name: String? = null,
  val accountName: String? = null,
  val accountType: String? = null,
  val ownerAccount: String? = null,
  val calSync1: String? = null,
  val color: String? = null,
  val isReadOnly: Boolean? = null,
  val supportsEvents: Boolean? = null,
  val supportsTasks: Boolean? = null,
  val isSubscription: Boolean? = null,
  val subscriptionUrl: String? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): PlatformCalendar {
      val id = __pigeon_list[0] as String?
      val name = __pigeon_list[1] as String?
      val accountName = __pigeon_list[2] as String?
      val accountType = __pigeon_list[3] as String?
      val ownerAccount = __pigeon_list[4] as String?
      val calSync1 = __pigeon_list[5] as String?
      val color = __pigeon_list[6] as String?
      val isReadOnly = __pigeon_list[7] as Boolean?
      val supportsEvents = __pigeon_list[8] as Boolean?
      val supportsTasks = __pigeon_list[9] as Boolean?
      val isSubscription = __pigeon_list[10] as Boolean?
      val subscriptionUrl = __pigeon_list[11] as String?
      return PlatformCalendar(id, name, accountName, accountType, ownerAccount, calSync1, color, isReadOnly, supportsEvents, supportsTasks, isSubscription, subscriptionUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      name,
      accountName,
      accountType,
      ownerAccount,
      calSync1,
      color,
      isReadOnly,
      supportsEvents,
      supportsTasks,
      isSubscription,
      subscriptionUrl,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformItem (
  val localId: String? = null,
  val uid: String? = null,
  val title: String? = null,
  val notes: String? = null,
  val location: String? = null,
  val eventTimezone: String? = null,
  val startTime: Long? = null,
  val endTime: Long? = null,
  val lastModified: Long? = null,
  val isTask: Boolean? = null,
  val isAllDay: Boolean? = null,
  val status: Long? = null,
  val priority: Long? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): PlatformItem {
      val localId = __pigeon_list[0] as String?
      val uid = __pigeon_list[1] as String?
      val title = __pigeon_list[2] as String?
      val notes = __pigeon_list[3] as String?
      val location = __pigeon_list[4] as String?
      val eventTimezone = __pigeon_list[5] as String?
      val startTime = __pigeon_list[6].let { num -> if (num is Int) num.toLong() else num as Long? }
      val endTime = __pigeon_list[7].let { num -> if (num is Int) num.toLong() else num as Long? }
      val lastModified = __pigeon_list[8].let { num -> if (num is Int) num.toLong() else num as Long? }
      val isTask = __pigeon_list[9] as Boolean?
      val isAllDay = __pigeon_list[10] as Boolean?
      val status = __pigeon_list[11].let { num -> if (num is Int) num.toLong() else num as Long? }
      val priority = __pigeon_list[12].let { num -> if (num is Int) num.toLong() else num as Long? }
      return PlatformItem(localId, uid, title, notes, location, eventTimezone, startTime, endTime, lastModified, isTask, isAllDay, status, priority)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      localId,
      uid,
      title,
      notes,
      location,
      eventTimezone,
      startTime,
      endTime,
      lastModified,
      isTask,
      isAllDay,
      status,
      priority,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CalendarEventRequest (
  val calendarId: String,
  val title: String,
  val start: Long,
  val end: Long,
  val notes: String? = null,
  val uid: String,
  val eventId: String? = null,
  val eventTimezone: String? = null,
  val location: String? = null,
  val isAllDay: Boolean? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): CalendarEventRequest {
      val calendarId = __pigeon_list[0] as String
      val title = __pigeon_list[1] as String
      val start = __pigeon_list[2].let { num -> if (num is Int) num.toLong() else num as Long }
      val end = __pigeon_list[3].let { num -> if (num is Int) num.toLong() else num as Long }
      val notes = __pigeon_list[4] as String?
      val uid = __pigeon_list[5] as String
      val eventId = __pigeon_list[6] as String?
      val eventTimezone = __pigeon_list[7] as String?
      val location = __pigeon_list[8] as String?
      val isAllDay = __pigeon_list[9] as Boolean?
      return CalendarEventRequest(calendarId, title, start, end, notes, uid, eventId, eventTimezone, location, isAllDay)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      calendarId,
      title,
      start,
      end,
      notes,
      uid,
      eventId,
      eventTimezone,
      location,
      isAllDay,
    )
  }
}

private object NativeCalendarApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CalendarEventRequest.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCalendar.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformItem.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CalendarEventRequest -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PlatformCalendar -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PlatformItem -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 定义原生侧必须实现的方法
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeCalendarApi {
  /** 获取日历列表前请求权限 */
  fun requestPermission(forTask: Boolean, callback: (Result<Boolean>) -> Unit)
  /** 获取所有可同步的日历 */
  fun getCalendars(): List<PlatformCalendar>
  /**
   * 获取指定日历在时间范围内的所有条目
   * 注意：Android 上由于系统限制，可能只返回 Event
   */
  fun getEvents(calendarId: String, startMs: Long, endMs: Long): List<PlatformItem>
  /**
   * 🚀 关键新增：在手机系统里创建一个新的日历账簿
   * 返回系统分配的数字 ID (String 形式的 Long)
   */
  fun createCalendar(displayName: String, accountName: String, color: Long, callback: (Result<String?>) -> Unit)
  /**
   * 🚀 关键新增：根据 ID 删除整个日历账簿
   * Android 上删除日历会自动联级删除该日历下的所有事件 (Events)
   */
  fun deleteCalendar(calendarId: String, accountName: String, callback: (Result<Boolean>) -> Unit)
  fun createEvent(calendarId: String, title: String, start: Long, end: Long, notes: String?, uid: String?, location: String?, eventTimezone: String?, isAllDay: Boolean?, callback: (Result<String?>) -> Unit)
  fun createOrUpdateEvent(request: CalendarEventRequest, callback: (Result<String?>) -> Unit)
  /** 获取指定日历下所有事件的 ID 列表（用于检测本地删除了哪些） */
  fun getSystemEventIds(calendarId: String, startMs: Long, endMs: Long): List<String>
  /** 根据 ID 删除本地事件（用于同步云端的删除操作） */
  fun deleteEvent(eventId: String): Boolean
  fun modifyCalendarTitle(calendarId: String, newTitle: String, accountName: String, accountType: String, callback: (Result<Boolean>) -> Unit)
  fun setCalendarEnabled(calendarId: String, accountName: String, enabled: Boolean, callback: (Result<Boolean>) -> Unit)
  fun normalizeMirrorCalendarPresentation(calendarId: String, callback: (Result<Boolean>) -> Unit)
  fun isCalendarAccountSyncEnabled(accountName: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by NativeCalendarApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeCalendarApiCodec
    }
    /** Sets up an instance of `NativeCalendarApi` to handle messages through the `binaryMessenger`. */
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeCalendarApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val forTaskArg = args[0] as Boolean
            api.requestPermission(forTaskArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.getCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.getCalendars())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.getEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val startMsArg = args[1].let { num -> if (num is Int) num.toLong() else num as Long }
            val endMsArg = args[2].let { num -> if (num is Int) num.toLong() else num as Long }
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.getEvents(calendarIdArg, startMsArg, endMsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.createCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val displayNameArg = args[0] as String
            val accountNameArg = args[1] as String
            val colorArg = args[2].let { num -> if (num is Int) num.toLong() else num as Long }
            api.createCalendar(displayNameArg, accountNameArg, colorArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val accountNameArg = args[1] as String
            api.deleteCalendar(calendarIdArg, accountNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.createEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val titleArg = args[1] as String
            val startArg = args[2].let { num -> if (num is Int) num.toLong() else num as Long }
            val endArg = args[3].let { num -> if (num is Int) num.toLong() else num as Long }
            val notesArg = args[4] as String?
            val uidArg = args[5] as String?
            val locationArg = args[6] as String?
            val eventTimezoneArg = args[7] as String?
            val isAllDayArg = args[8] as Boolean?
            api.createEvent(calendarIdArg, titleArg, startArg, endArg, notesArg, uidArg, locationArg, eventTimezoneArg, isAllDayArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.createOrUpdateEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CalendarEventRequest
            api.createOrUpdateEvent(requestArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.getSystemEventIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val startMsArg = args[1] as Long
            val endMsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.getSystemEventIds(calendarIdArg, startMsArg, endMsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf<Any?>(api.deleteEvent(eventIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.modifyCalendarTitle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val newTitleArg = args[1] as String
            val accountNameArg = args[2] as String
            val accountTypeArg = args[3] as String
            api.modifyCalendarTitle(calendarIdArg, newTitleArg, accountNameArg, accountTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.setCalendarEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val accountNameArg = args[1] as String
            val enabledArg = args[2] as Boolean
            api.setCalendarEnabled(calendarIdArg, accountNameArg, enabledArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.normalizeMirrorCalendarPresentation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            api.normalizeMirrorCalendarPresentation(calendarIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caleesync.NativeCalendarApi.isCalendarAccountSyncEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountNameArg = args[0] as String
            api.isCalendarAccountSyncEnabled(accountNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
