// Autogenerated from Pigeon, do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.viso.caleesync

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> = listOf(result)

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is BackgroundSyncFlutterError) {
    listOf(exception.code, exception.message, exception.details)
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: ${exception.cause}, Stacktrace: ${Log.getStackTraceString(exception)}"
    )
  }
}

private class BackgroundSyncFlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BackgroundRunOutcome(val raw: Int) {
  SUCCESS(0),
  RETRY(1),
  FAILURE(2),
  GATED(3);

  companion object {
    fun ofRaw(raw: Int): BackgroundRunOutcome = values().firstOrNull { it.raw == raw }
      ?: throw IllegalArgumentException("Unknown BackgroundRunOutcome raw value: $raw")
  }
}

enum class BackgroundGateReason(val raw: Int) {
  NONE(0),
  NO_NETWORK(1),
  AUTH_INVALID(2),
  BINDING_INVALID(3),
  REPAIR_REQUIRED(4),
  ENVIRONMENT_BLOCKED(5),
  LOCAL_CALENDAR_MISSING(6),
  UNKNOWN(7);

  companion object {
    fun ofRaw(raw: Int): BackgroundGateReason = values().firstOrNull { it.raw == raw }
      ?: throw IllegalArgumentException("Unknown BackgroundGateReason raw value: $raw")
  }
}

data class BackgroundRunRequest(
  val trigger: String,
  val contractVersion: Long,
) {
  companion object {
    fun fromList(list: List<Any?>): BackgroundRunRequest {
      val trigger = list[0] as String
      val contractVersion = list[1].let { if (it is Int) it.toLong() else it as Long }
      return BackgroundRunRequest(trigger, contractVersion)
    }
  }

  fun toList(): List<Any?> = listOf(trigger, contractVersion)
}

data class BackgroundRunResult(
  val outcome: BackgroundRunOutcome,
  val reason: String,
  val gateReason: BackgroundGateReason,
  val error: String? = null,
  val contractVersion: Long,
) {
  companion object {
    fun fromList(list: List<Any?>): BackgroundRunResult {
      val outcome = BackgroundRunOutcome.ofRaw((list[0] as Number).toInt())
      val reason = list[1] as String
      val gateReason = BackgroundGateReason.ofRaw((list[2] as Number).toInt())
      val error = list[3] as String?
      val contractVersion = list[4].let { if (it is Int) it.toLong() else it as Long }
      return BackgroundRunResult(outcome, reason, gateReason, error, contractVersion)
    }
  }

  fun toList(): List<Any?> = listOf(outcome.raw, reason, gateReason.raw, error, contractVersion)
}

data class BackgroundStatusDto(
  val periodicEnabled: Boolean,
  val lastRunAtMs: Long? = null,
  val lastOutcome: BackgroundRunOutcome? = null,
  val lastReason: String? = null,
  val lastGateReason: BackgroundGateReason? = null,
  val lastError: String? = null,
  val nextScheduledAtMs: Long? = null,
  val workerRunning: Boolean,
  val intervalMinutes: Long,
  val contractVersion: Long,
) {
  companion object {
    fun fromList(list: List<Any?>): BackgroundStatusDto {
      val periodicEnabled = list[0] as Boolean
      val lastRunAtMs = list[1].let { if (it is Int) it.toLong() else it as Long? }
      val lastOutcome = (list[2] as Number?)?.toInt()?.let { BackgroundRunOutcome.ofRaw(it) }
      val lastReason = list[3] as String?
      val lastGateReason = (list[4] as Number?)?.toInt()?.let { BackgroundGateReason.ofRaw(it) }
      val lastError = list[5] as String?
      val nextScheduledAtMs = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val workerRunning = list[7] as Boolean
      val intervalMinutes = list[8].let { if (it is Int) it.toLong() else it as Long }
      val contractVersion = list[9].let { if (it is Int) it.toLong() else it as Long }
      return BackgroundStatusDto(
        periodicEnabled,
        lastRunAtMs,
        lastOutcome,
        lastReason,
        lastGateReason,
        lastError,
        nextScheduledAtMs,
        workerRunning,
        intervalMinutes,
        contractVersion,
      )
    }
  }

  fun toList(): List<Any?> = listOf(
    periodicEnabled,
    lastRunAtMs,
    lastOutcome?.raw,
    lastReason,
    lastGateReason?.raw,
    lastError,
    nextScheduledAtMs,
    workerRunning,
    intervalMinutes,
    contractVersion,
  )
}

private object BackgroundSyncApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> (readValue(buffer) as? List<Any?>)?.let { BackgroundRunRequest.fromList(it) }
      130.toByte() -> (readValue(buffer) as? List<Any?>)?.let { BackgroundRunResult.fromList(it) }
      131.toByte() -> (readValue(buffer) as? List<Any?>)?.let { BackgroundStatusDto.fromList(it) }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is BackgroundRunRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BackgroundRunResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BackgroundStatusDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

interface BackgroundSyncControlApi {
  fun schedulePeriodic(intervalMinutes: Long, callback: (Result<Unit>) -> Unit)
  fun cancelPeriodic(callback: (Result<Unit>) -> Unit)
  fun ensurePeriodicScheduled(intervalMinutes: Long, callback: (Result<Unit>) -> Unit)
  fun enqueueOneOff(reason: String, expedited: Boolean, callback: (Result<Unit>) -> Unit)
  fun getBackgroundStatus(callback: (Result<BackgroundStatusDto>) -> Unit)

  companion object {
    val codec: MessageCodec<Any?> by lazy { BackgroundSyncApiCodec }

    fun setUp(binaryMessenger: BinaryMessenger, api: BackgroundSyncControlApi?, messageChannelSuffix: String = "") {
      val suffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""

      val scheduleChannel = BasicMessageChannel<Any?>(
        binaryMessenger,
        "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.schedulePeriodic$suffix",
        codec,
      )
      if (api == null) {
        scheduleChannel.setMessageHandler(null)
      } else {
        scheduleChannel.setMessageHandler { message, reply ->
          val args = message as List<Any?>
          val interval = args[0].let { if (it is Int) it.toLong() else it as Long }
          api.schedulePeriodic(interval) { result ->
            result.fold(
              onSuccess = { reply.reply(wrapResult(null)) },
              onFailure = { reply.reply(wrapError(it)) },
            )
          }
        }
      }

      val cancelChannel = BasicMessageChannel<Any?>(
        binaryMessenger,
        "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.cancelPeriodic$suffix",
        codec,
      )
      if (api == null) {
        cancelChannel.setMessageHandler(null)
      } else {
        cancelChannel.setMessageHandler { _, reply ->
          api.cancelPeriodic { result ->
            result.fold(
              onSuccess = { reply.reply(wrapResult(null)) },
              onFailure = { reply.reply(wrapError(it)) },
            )
          }
        }
      }

      val ensureChannel = BasicMessageChannel<Any?>(
        binaryMessenger,
        "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.ensurePeriodicScheduled$suffix",
        codec,
      )
      if (api == null) {
        ensureChannel.setMessageHandler(null)
      } else {
        ensureChannel.setMessageHandler { message, reply ->
          val args = message as List<Any?>
          val interval = args[0].let { if (it is Int) it.toLong() else it as Long }
          api.ensurePeriodicScheduled(interval) { result ->
            result.fold(
              onSuccess = { reply.reply(wrapResult(null)) },
              onFailure = { reply.reply(wrapError(it)) },
            )
          }
        }
      }

      val enqueueChannel = BasicMessageChannel<Any?>(
        binaryMessenger,
        "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.enqueueOneOff$suffix",
        codec,
      )
      if (api == null) {
        enqueueChannel.setMessageHandler(null)
      } else {
        enqueueChannel.setMessageHandler { message, reply ->
          val args = message as List<Any?>
          val reason = args[0] as String
          val expedited = args[1] as Boolean
          api.enqueueOneOff(reason, expedited) { result ->
            result.fold(
              onSuccess = { reply.reply(wrapResult(null)) },
              onFailure = { reply.reply(wrapError(it)) },
            )
          }
        }
      }

      val statusChannel = BasicMessageChannel<Any?>(
        binaryMessenger,
        "dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.getBackgroundStatus$suffix",
        codec,
      )
      if (api == null) {
        statusChannel.setMessageHandler(null)
      } else {
        statusChannel.setMessageHandler { _, reply ->
          api.getBackgroundStatus { result ->
            result.fold(
              onSuccess = { reply.reply(wrapResult(it)) },
              onFailure = { reply.reply(wrapError(it)) },
            )
          }
        }
      }
    }
  }
}

class BackgroundSyncRunnerApi(
  private val binaryMessenger: BinaryMessenger,
  private val messageChannelSuffix: String = "",
) {
  companion object {
    val codec: MessageCodec<Any?> by lazy { BackgroundSyncApiCodec }
  }

  fun runBackgroundSync(request: BackgroundRunRequest, callback: (Result<BackgroundRunResult>) -> Unit) {
    val suffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.caleesync.BackgroundSyncRunnerApi.runBackgroundSync$suffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(request)) { reply ->
      val listReply = reply as List<Any?>?
      if (listReply == null) {
        callback(Result.failure(FlutterError("channel-error", "Unable to establish connection on channel: '$channelName'.")))
      } else if (listReply.size > 1) {
        callback(Result.failure(FlutterError(listReply[0] as String, listReply[1] as String?, listReply[2])))
      } else {
        val output = listReply[0] as BackgroundRunResult?
        if (output == null) {
          callback(Result.failure(FlutterError("null-error", "Host platform returned null value for non-null return value.")))
        } else {
          callback(Result.success(output))
        }
      }
    }
  }
}
