// Autogenerated from Pigeon, do not edit directly.
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as

import 'dart:async';
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum BackgroundRunOutcome {
  success,
  retry,
  failure,
  gated,
}

enum BackgroundGateReason {
  none,
  noNetwork,
  authInvalid,
  bindingInvalid,
  repairRequired,
  environmentBlocked,
  localCalendarMissing,
  unknown,
}

const int kBackgroundSyncContractVersion = 1;

class BackgroundRunRequest {
  BackgroundRunRequest({required this.trigger, required this.contractVersion});

  String trigger;
  int contractVersion;

  Object encode() => <Object?>[trigger, contractVersion];

  static BackgroundRunRequest decode(Object result) {
    result as List<Object?>;
    return BackgroundRunRequest(
      trigger: result[0]! as String,
      contractVersion: (result[1]! as num).toInt(),
    );
  }
}

class BackgroundRunResult {
  BackgroundRunResult({
    required this.outcome,
    required this.reason,
    required this.gateReason,
    this.error,
    required this.contractVersion,
  });

  BackgroundRunOutcome outcome;
  String reason;
  BackgroundGateReason gateReason;
  String? error;
  int contractVersion;

  Object encode() => <Object?>[outcome.index, reason, gateReason.index, error, contractVersion];

  static BackgroundRunResult decode(Object result) {
    result as List<Object?>;
    return BackgroundRunResult(
      outcome: BackgroundRunOutcome.values[(result[0]! as num).toInt()],
      reason: result[1]! as String,
      gateReason: BackgroundGateReason.values[(result[2]! as num).toInt()],
      error: result[3] as String?,
      contractVersion: (result[4]! as num).toInt(),
    );
  }
}

class BackgroundStatusDto {
  BackgroundStatusDto({
    required this.periodicEnabled,
    this.lastRunAtMs,
    this.lastOutcome,
    this.lastReason,
    this.lastGateReason,
    this.lastError,
    this.nextScheduledAtMs,
    required this.workerRunning,
    required this.intervalMinutes,
    required this.contractVersion,
  });

  bool periodicEnabled;
  int? lastRunAtMs;
  BackgroundRunOutcome? lastOutcome;
  String? lastReason;
  BackgroundGateReason? lastGateReason;
  String? lastError;
  int? nextScheduledAtMs;
  bool workerRunning;
  int intervalMinutes;
  int contractVersion;

  Object encode() => <Object?>[
        periodicEnabled,
        lastRunAtMs,
        lastOutcome?.index,
        lastReason,
        lastGateReason?.index,
        lastError,
        nextScheduledAtMs,
        workerRunning,
        intervalMinutes,
        contractVersion,
      ];

  static BackgroundStatusDto decode(Object result) {
    result as List<Object?>;
    return BackgroundStatusDto(
      periodicEnabled: result[0]! as bool,
      lastRunAtMs: (result[1] as num?)?.toInt(),
      lastOutcome: result[2] == null ? null : BackgroundRunOutcome.values[(result[2]! as num).toInt()],
      lastReason: result[3] as String?,
      lastGateReason: result[4] == null ? null : BackgroundGateReason.values[(result[4]! as num).toInt()],
      lastError: result[5] as String?,
      nextScheduledAtMs: (result[6] as num?)?.toInt(),
      workerRunning: result[7]! as bool,
      intervalMinutes: (result[8]! as num).toInt(),
      contractVersion: (result[9]! as num).toInt(),
    );
  }
}

class _BackgroundSyncApiCodec extends StandardMessageCodec {
  const _BackgroundSyncApiCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BackgroundRunRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is BackgroundRunResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is BackgroundStatusDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return BackgroundRunRequest.decode(readValue(buffer)!);
      case 130:
        return BackgroundRunResult.decode(readValue(buffer)!);
      case 131:
        return BackgroundStatusDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BackgroundSyncControlApi {
  BackgroundSyncControlApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : _binaryMessenger = binaryMessenger,
        _suffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  static const int contractVersion = kBackgroundSyncContractVersion;
  final BinaryMessenger? _binaryMessenger;
  final String _suffix;
  static const MessageCodec<Object?> pigeonChannelCodec = _BackgroundSyncApiCodec();

  Future<void> schedulePeriodic(int intervalMinutes) async {
    final channelName = 'dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.schedulePeriodic$_suffix';
    final channel = BasicMessageChannel<Object?>(channelName, pigeonChannelCodec, binaryMessenger: _binaryMessenger);
    final reply = await channel.send(<Object?>[intervalMinutes]) as List<Object?>?;
    if (reply == null) throw _createConnectionError(channelName);
    if (reply.length > 1) {
      throw PlatformException(code: reply[0]! as String, message: reply[1] as String?, details: reply[2]);
    }
  }

  Future<void> cancelPeriodic() async {
    final channelName = 'dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.cancelPeriodic$_suffix';
    final channel = BasicMessageChannel<Object?>(channelName, pigeonChannelCodec, binaryMessenger: _binaryMessenger);
    final reply = await channel.send(null) as List<Object?>?;
    if (reply == null) throw _createConnectionError(channelName);
    if (reply.length > 1) {
      throw PlatformException(code: reply[0]! as String, message: reply[1] as String?, details: reply[2]);
    }
  }

  Future<void> ensurePeriodicScheduled(int intervalMinutes) async {
    final channelName = 'dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.ensurePeriodicScheduled$_suffix';
    final channel = BasicMessageChannel<Object?>(channelName, pigeonChannelCodec, binaryMessenger: _binaryMessenger);
    final reply = await channel.send(<Object?>[intervalMinutes]) as List<Object?>?;
    if (reply == null) throw _createConnectionError(channelName);
    if (reply.length > 1) {
      throw PlatformException(code: reply[0]! as String, message: reply[1] as String?, details: reply[2]);
    }
  }

  Future<void> enqueueOneOff(String reason, bool expedited) async {
    final channelName = 'dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.enqueueOneOff$_suffix';
    final channel = BasicMessageChannel<Object?>(channelName, pigeonChannelCodec, binaryMessenger: _binaryMessenger);
    final reply = await channel.send(<Object?>[reason, expedited]) as List<Object?>?;
    if (reply == null) throw _createConnectionError(channelName);
    if (reply.length > 1) {
      throw PlatformException(code: reply[0]! as String, message: reply[1] as String?, details: reply[2]);
    }
  }

  Future<BackgroundStatusDto> getBackgroundStatus() async {
    final channelName = 'dev.flutter.pigeon.caleesync.BackgroundSyncControlApi.getBackgroundStatus$_suffix';
    final channel = BasicMessageChannel<Object?>(channelName, pigeonChannelCodec, binaryMessenger: _binaryMessenger);
    final reply = await channel.send(null) as List<Object?>?;
    if (reply == null) throw _createConnectionError(channelName);
    if (reply.length > 1) {
      throw PlatformException(code: reply[0]! as String, message: reply[1] as String?, details: reply[2]);
    }
    if (reply[0] == null) {
      throw PlatformException(code: 'null-error', message: 'Host platform returned null value for non-null return value.');
    }
    return reply[0]! as BackgroundStatusDto;
  }
}

abstract class BackgroundSyncRunnerApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _BackgroundSyncApiCodec();

  Future<BackgroundRunResult> runBackgroundSync(BackgroundRunRequest request);

  static void setUp(BackgroundSyncRunnerApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''}) {
    final suffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    final channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.caleesync.BackgroundSyncRunnerApi.runBackgroundSync$suffix',
      pigeonChannelCodec,
      binaryMessenger: binaryMessenger,
    );
    if (api == null) {
      channel.setMessageHandler(null);
    } else {
      channel.setMessageHandler((message) async {
        final args = message as List<Object?>;
        final output = await api.runBackgroundSync(args[0]! as BackgroundRunRequest);
        return <Object?>[output];
      });
    }
  }
}
