// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Calendar data contract exposed via Pigeon.
///
/// Scope (first milestone):
/// - List calendars
/// - List events within a time window
///
/// Note: Permission handling is done via permission_handler in Flutter,
/// not through this Pigeon API.
class TimeWindow {
  TimeWindow({
    required this.startMillis,
    required this.endMillis,
    this.calendarIds,
  });

  /// Inclusive UTC start timestamp in milliseconds.
  int startMillis;

  /// Exclusive UTC end timestamp in milliseconds.
  int endMillis;

  /// Optional filter for specific calendar IDs (device identifiers).
  List<int?>? calendarIds;

  Object encode() {
    return <Object?>[
      startMillis,
      endMillis,
      calendarIds,
    ];
  }

  static TimeWindow decode(Object result) {
    result as List<Object?>;
    return TimeWindow(
      startMillis: result[0]! as int,
      endMillis: result[1]! as int,
      calendarIds: (result[2] as List<Object?>?)?.cast<int?>(),
    );
  }
}

class PigeonCalendar {
  PigeonCalendar({
    required this.id,
    required this.accountName,
    required this.accountType,
    this.ownerAccount,
    this.name,
    this.displayName,
    required this.color,
    required this.visible,
    required this.syncEvents,
    required this.isPrimary,
    required this.isLocal,
    required this.accessLevel,
  });

  /// Device-level calendar identifier (Calendar Provider / EventKit).
  int id;

  String accountName;

  String accountType;

  String? ownerAccount;

  String? name;

  String? displayName;

  int color;

  bool visible;

  bool syncEvents;

  bool isPrimary;

  bool isLocal;

  int accessLevel;

  Object encode() {
    return <Object?>[
      id,
      accountName,
      accountType,
      ownerAccount,
      name,
      displayName,
      color,
      visible,
      syncEvents,
      isPrimary,
      isLocal,
      accessLevel,
    ];
  }

  static PigeonCalendar decode(Object result) {
    result as List<Object?>;
    return PigeonCalendar(
      id: result[0]! as int,
      accountName: result[1]! as String,
      accountType: result[2]! as String,
      ownerAccount: result[3] as String?,
      name: result[4] as String?,
      displayName: result[5] as String?,
      color: result[6]! as int,
      visible: result[7]! as bool,
      syncEvents: result[8]! as bool,
      isPrimary: result[9]! as bool,
      isLocal: result[10]! as bool,
      accessLevel: result[11]! as int,
    );
  }
}

class PigeonEvent {
  PigeonEvent({
    required this.id,
    required this.calendarId,
    required this.title,
    required this.startMillis,
    required this.endMillis,
    this.description,
    this.location,
    this.allDay = false,
    this.timeZone,
    this.recurrenceRule,
    this.recurrenceExceptionMillis,
    this.attendees,
    this.organizer,
    this.status,
    this.etag,
    this.updatedAtMillis,
    this.isCanceled = false,
  });

  /// Device-level event identifier (Calendar Provider / EventKit).
  String id;

  String calendarId;

  String title;

  int startMillis;

  int endMillis;

  String? description;

  String? location;

  bool allDay;

  String? timeZone;

  /// RRULE string (e.g. FREQ=WEEKLY;BYDAY=MO,WE,FR).
  String? recurrenceRule;

  /// UTC millis for EXDATE-like exceptions.
  List<int?>? recurrenceExceptionMillis;

  /// Attendee emails or identifiers.
  List<String?>? attendees;

  String? organizer;

  String? status;

  String? etag;

  int? updatedAtMillis;

  bool isCanceled;

  Object encode() {
    return <Object?>[
      id,
      calendarId,
      title,
      startMillis,
      endMillis,
      description,
      location,
      allDay,
      timeZone,
      recurrenceRule,
      recurrenceExceptionMillis,
      attendees,
      organizer,
      status,
      etag,
      updatedAtMillis,
      isCanceled,
    ];
  }

  static PigeonEvent decode(Object result) {
    result as List<Object?>;
    return PigeonEvent(
      id: result[0]! as String,
      calendarId: result[1]! as String,
      title: result[2]! as String,
      startMillis: result[3]! as int,
      endMillis: result[4]! as int,
      description: result[5] as String?,
      location: result[6] as String?,
      allDay: result[7]! as bool,
      timeZone: result[8] as String?,
      recurrenceRule: result[9] as String?,
      recurrenceExceptionMillis: (result[10] as List<Object?>?)?.cast<int?>(),
      attendees: (result[11] as List<Object?>?)?.cast<String?>(),
      organizer: result[12] as String?,
      status: result[13] as String?,
      etag: result[14] as String?,
      updatedAtMillis: result[15] as int?,
      isCanceled: result[16]! as bool,
    );
  }
}

class _CalendarHostApiCodec extends StandardMessageCodec {
  const _CalendarHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonCalendar) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is TimeWindow) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonCalendar.decode(readValue(buffer)!);
      case 129: 
        return PigeonEvent.decode(readValue(buffer)!);
      case 130: 
        return TimeWindow.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API implemented on Android/iOS. Flutter calls into this.
///
/// Note: Permission must be granted before calling these methods.
/// Use permission_handler in Flutter to request calendar permissions.
class CalendarHostApi {
  /// Constructor for [CalendarHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CalendarHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _CalendarHostApiCodec();

  final String __pigeon_messageChannelSuffix;

  /// List calendars available on the device.
  ///
  /// Throws if permission is not granted.
  Future<List<PigeonCalendar?>> listCalendars() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.calendar_api.CalendarHostApi.listCalendars$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PigeonCalendar?>();
    }
  }

  /// List events in the given UTC time window (can filter calendars).
  ///
  /// Throws if permission is not granted.
  Future<List<PigeonEvent?>> listEvents(TimeWindow window) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.calendar_api.CalendarHostApi.listEvents$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[window]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PigeonEvent?>();
    }
  }
}
