// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// 配置 Pigeon 生成代码的路径
class PlatformCalendar {
  PlatformCalendar({
    this.id,
    this.name,
    this.accountName,
    this.accountType,
    this.ownerAccount,
    this.calSync1,
    this.color,
    this.isReadOnly,
    this.supportsEvents,
    this.supportsTasks,
    this.isSubscription,
    this.subscriptionUrl,
  });

  String? id;

  String? name;

  String? accountName;

  String? accountType;

  String? ownerAccount;

  String? calSync1;

  String? color;

  bool? isReadOnly;

  bool? supportsEvents;

  bool? supportsTasks;

  bool? isSubscription;

  String? subscriptionUrl;

  Object encode() {
    return <Object?>[
      id,
      name,
      accountName,
      accountType,
      ownerAccount,
      calSync1,
      color,
      isReadOnly,
      supportsEvents,
      supportsTasks,
      isSubscription,
      subscriptionUrl,
    ];
  }

  static PlatformCalendar decode(Object result) {
    result as List<Object?>;
    return PlatformCalendar(
      id: result[0] as String?,
      name: result[1] as String?,
      accountName: result[2] as String?,
      accountType: result[3] as String?,
      ownerAccount: result[4] as String?,
      calSync1: result[5] as String?,
      color: result[6] as String?,
      isReadOnly: result[7] as bool?,
      supportsEvents: result[8] as bool?,
      supportsTasks: result[9] as bool?,
      isSubscription: result[10] as bool?,
      subscriptionUrl: result[11] as String?,
    );
  }
}

class PlatformItem {
  PlatformItem({
    this.localId,
    this.uid,
    this.title,
    this.notes,
    this.location,
    this.eventTimezone,
    this.startTime,
    this.endTime,
    this.lastModified,
    this.isTask,
    this.isAllDay,
    this.status,
    this.priority,
  });

  String? localId;

  String? uid;

  String? title;

  String? notes;

  String? location;

  String? eventTimezone;

  int? startTime;

  int? endTime;

  int? lastModified;

  bool? isTask;

  bool? isAllDay;

  int? status;

  int? priority;

  Object encode() {
    return <Object?>[
      localId,
      uid,
      title,
      notes,
      location,
      eventTimezone,
      startTime,
      endTime,
      lastModified,
      isTask,
      isAllDay,
      status,
      priority,
    ];
  }

  static PlatformItem decode(Object result) {
    result as List<Object?>;
    return PlatformItem(
      localId: result[0] as String?,
      uid: result[1] as String?,
      title: result[2] as String?,
      notes: result[3] as String?,
      location: result[4] as String?,
      eventTimezone: result[5] as String?,
      startTime: result[6] as int?,
      endTime: result[7] as int?,
      lastModified: result[8] as int?,
      isTask: result[9] as bool?,
      isAllDay: result[10] as bool?,
      status: result[11] as int?,
      priority: result[12] as int?,
    );
  }
}

class CalendarEventRequest {
  CalendarEventRequest({
    required this.calendarId,
    required this.title,
    required this.start,
    required this.end,
    this.notes,
    required this.uid,
    this.eventId,
    this.eventTimezone,
    this.location,
    this.isAllDay,
  });

  String calendarId;

  String title;

  int start;

  int end;

  String? notes;

  String uid;

  String? eventId;

  String? eventTimezone;

  String? location;

  bool? isAllDay;

  Object encode() {
    return <Object?>[
      calendarId,
      title,
      start,
      end,
      notes,
      uid,
      eventId,
      eventTimezone,
      location,
      isAllDay,
    ];
  }

  static CalendarEventRequest decode(Object result) {
    result as List<Object?>;
    return CalendarEventRequest(
      calendarId: result[0]! as String,
      title: result[1]! as String,
      start: result[2]! as int,
      end: result[3]! as int,
      notes: result[4] as String?,
      uid: result[5]! as String,
      eventId: result[6] as String?,
      eventTimezone: result[7] as String?,
      location: result[8] as String?,
      isAllDay: result[9] as bool?,
    );
  }
}

class _NativeCalendarApiCodec extends StandardMessageCodec {
  const _NativeCalendarApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CalendarEventRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCalendar) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PlatformItem) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CalendarEventRequest.decode(readValue(buffer)!);
      case 129: 
        return PlatformCalendar.decode(readValue(buffer)!);
      case 130: 
        return PlatformItem.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// 定义原生侧必须实现的方法
class NativeCalendarApi {
  /// Constructor for [NativeCalendarApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeCalendarApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _NativeCalendarApiCodec();

  final String __pigeon_messageChannelSuffix;

  /// 获取日历列表前请求权限
  Future<bool> requestPermission(bool forTask) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.requestPermission$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[forTask]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// 获取所有可同步的日历
  Future<List<PlatformCalendar?>> getCalendars() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.getCalendars$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PlatformCalendar?>();
    }
  }

  /// 获取指定日历在时间范围内的所有条目
  /// 注意：Android 上由于系统限制，可能只返回 Event
  Future<List<PlatformItem?>> getEvents(String calendarId, int startMs, int endMs) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.getEvents$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, startMs, endMs]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PlatformItem?>();
    }
  }

  /// 🚀 关键新增：在手机系统里创建一个新的日历账簿
  /// 返回系统分配的数字 ID (String 形式的 Long)
  Future<String?> createCalendar(String displayName, String accountName, int color) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.createCalendar$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[displayName, accountName, color]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return (__pigeon_replyList[0] as String?);
    }
  }

  /// 🚀 关键新增：根据 ID 删除整个日历账簿
  /// Android 上删除日历会自动联级删除该日历下的所有事件 (Events)
  Future<bool> deleteCalendar(String calendarId, String accountName) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteCalendar$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, accountName]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<String?> createEvent(
    String calendarId,
    String title,
    int start,
    int end,
    String? notes,
    String? uid,
    String? location,
    String? eventTimezone,
    bool? isAllDay,
  ) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.createEvent$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[
      calendarId,
      title,
      start,
      end,
      notes,
      uid,
      location,
      eventTimezone,
      isAllDay,
    ]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return (__pigeon_replyList[0] as String?);
    }
  }

  Future<String?> createOrUpdateEvent(CalendarEventRequest request) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.createOrUpdateEvent$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[request]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return (__pigeon_replyList[0] as String?);
    }
  }

  /// 获取指定日历下所有事件的 ID 列表（用于检测本地删除了哪些）
  Future<List<String?>> getSystemEventIds(String calendarId, int startMs, int endMs) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.getSystemEventIds$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, startMs, endMs]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<String?>();
    }
  }

  /// 根据 ID 删除本地事件（用于同步云端的删除操作）
  Future<bool> deleteEvent(String eventId) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteEvent$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[eventId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<bool> modifyCalendarTitle(String calendarId, String newTitle, String accountName, String accountType) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.modifyCalendarTitle$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, newTitle, accountName, accountType]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<bool> setCalendarEnabled(String calendarId, String accountName, bool enabled) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.setCalendarEnabled$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, accountName, enabled]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<bool> isCalendarAccountSyncEnabled(String accountName) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.isCalendarAccountSyncEnabled$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[accountName]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }
}
