// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// 配置 Pigeon 生成代码的路径
class PlatformCalendar {
  PlatformCalendar({
    this.id,
    this.name,
    this.color,
    this.isReadOnly,
    this.supportsEvents,
    this.supportsTasks,
  });

  String? id;

  String? name;

  String? color;

  bool? isReadOnly;

  bool? supportsEvents;

  bool? supportsTasks;

  Object encode() {
    return <Object?>[
      id,
      name,
      color,
      isReadOnly,
      supportsEvents,
      supportsTasks,
    ];
  }

  static PlatformCalendar decode(Object result) {
    result as List<Object?>;
    return PlatformCalendar(
      id: result[0] as String?,
      name: result[1] as String?,
      color: result[2] as String?,
      isReadOnly: result[3] as bool?,
      supportsEvents: result[4] as bool?,
      supportsTasks: result[5] as bool?,
    );
  }
}

class PlatformItem {
  PlatformItem({
    this.localId,
    this.uid,
    this.title,
    this.notes,
    this.location,
    this.startTime,
    this.endTime,
    this.lastModified,
    this.isTask,
    this.isAllDay,
    this.status,
    this.priority,
  });

  String? localId;

  String? uid;

  String? title;

  String? notes;

  String? location;

  int? startTime;

  int? endTime;

  int? lastModified;

  bool? isTask;

  bool? isAllDay;

  int? status;

  int? priority;

  Object encode() {
    return <Object?>[
      localId,
      uid,
      title,
      notes,
      location,
      startTime,
      endTime,
      lastModified,
      isTask,
      isAllDay,
      status,
      priority,
    ];
  }

  static PlatformItem decode(Object result) {
    result as List<Object?>;
    return PlatformItem(
      localId: result[0] as String?,
      uid: result[1] as String?,
      title: result[2] as String?,
      notes: result[3] as String?,
      location: result[4] as String?,
      startTime: result[5] as int?,
      endTime: result[6] as int?,
      lastModified: result[7] as int?,
      isTask: result[8] as bool?,
      isAllDay: result[9] as bool?,
      status: result[10] as int?,
      priority: result[11] as int?,
    );
  }
}

class _NativeCalendarApiCodec extends StandardMessageCodec {
  const _NativeCalendarApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PlatformCalendar) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PlatformItem) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PlatformItem) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PlatformCalendar.decode(readValue(buffer)!);
      case 129: 
        return PlatformItem.decode(readValue(buffer)!);
      case 130: 
        return PlatformItem.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// 定义原生侧必须实现的方法
class NativeCalendarApi {
  /// Constructor for [NativeCalendarApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeCalendarApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _NativeCalendarApiCodec();

  final String __pigeon_messageChannelSuffix;

  /// 获取日历列表前请求权限
  Future<bool> requestPermission(bool forTask) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.requestPermission$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[forTask]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// 获取所有可同步的日历
  Future<List<PlatformCalendar?>> getCalendars() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.getCalendars$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PlatformCalendar?>();
    }
  }

  /// 获取指定日历在时间范围内的所有条目
  /// 注意：Android 上由于系统限制，可能只返回 Event
  Future<List<PlatformItem?>> getItems(String calendarId, int startMs, int endMs) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.getItems$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, startMs, endMs]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PlatformItem?>();
    }
  }

  /// 创建或更新条目
  /// 返回写入成功后的系统 localId
  Future<String> upsertItem(String calendarId, PlatformItem item) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.upsertItem$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[calendarId, item]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  /// 根据 ID 删除条目
  Future<void> deleteItem(String localId) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.caleesync.NativeCalendarApi.deleteItem$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[localId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}
